//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONEL
    {
        public int PersonelID { get; set; }
        public string AdıSoyadi { get; set; }
        public string TC { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> IseGirisTarihi { get; set; }
        public Nullable<System.DateTime> IstenCikisTarihi { get; set; }
        public Nullable<int> Departman { get; set; }
        public Nullable<int> Gorev { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Durum { get; set; }
    
        public virtual TBLDEPARTMAN TBLDEPARTMAN { get; set; }
        public virtual TBLDURUM TBLDURUM { get; set; }
        public virtual TBLGOREV TBLGOREV { get; set; }
    }
}
